### ISSUE TITLE
rendered dataset and trainning script

### ISSUE THREAD

**Issue by Bycqg** [iSEE-Laboratory/DreamView#4]
1. as mentioned in TODO, will the rendered dataset still be released?
2. does text to 3D generation require training? if necessary, is there no corresponding training script in the project?

**Comment by yanjk3** [comment]
1. Well unfortunately, it may not be easy for me to release the rendered dataset since I have resigned from TongYi Lab for quite a long time. I think the render setting is stated in detail in our paper. And lastly, the dataset is built based on [Cap3D](https://github.com/crockwell/Cap3D/tree/main/captioning_pipeline), and I believe you can find something useful there. 
2. 3D generation requires training, it trains a 3D representation, i.e., Nerf. The training script can be found [here](https://github.com/iSEE-Laboratory/DreamView/blob/main/DreamView-3D/reproduce.sh), you can modify the prompt and try it yourself. Have fun~

**Comment by Bycqg** [comment]
thank you for your reply
